/**
 * Educational tooltip content for every input/output parameter
 */

export interface TooltipContent {
  title: string;
  description: string;
  typical: string;
  effect: string;
}

export const tooltips: Record<string, TooltipContent> = {
  // Input parameters
  head: {
    title: "Head (h)",
    description:
      "The vertical distance between the water surface in the reservoir and the turbine. Also called hydraulic head.",
    typical:
      "Low head: 2-30 m (river dams). Medium head: 30-100 m (reservoir dams). High head: 100-1000 m+ (mountain installations).",
    effect:
      "Power output is directly proportional to head. Doubling head doubles power output.",
  },
  flowRate: {
    title: "Flow Rate (Q)",
    description:
      "The volume of water passing through the turbine per second, measured in cubic meters per second (m^3/s).",
    typical:
      "Micro plants: 0.1-5 m^3/s. Mini plants: 5-50 m^3/s. Large plants: 100-5000+ m^3/s.",
    effect:
      "Power output is directly proportional to flow rate. Doubling flow doubles power output.",
  },
  efficiency: {
    title: "Turbine Efficiency (eta)",
    description:
      "The ratio of useful mechanical/electrical output to the total water energy input.",
    typical:
      "Modern turbines: 85-95%. Pelton: 85-92%. Francis: 90-95%. Kaplan: 88-93%.",
    effect:
      "Efficiency directly scales power output.",
  },
  plantType: {
    title: "Plant Type",
    description:
      "The classification of the hydropower plant based on installed capacity.",
    typical:
      "Micro: <100 kW. Mini: 100 kW-10 MW. Small: 10-30 MW. Large: >30 MW.",
    effect:
      "Selecting a plant type provides suggested flow ranges for realistic parameter selection.",
  },

  // Output parameters
  powerOutput: {
    title: "Power Output (P)",
    description:
      "The theoretical instantaneous power generated by the plant: P = eta x rho x g x h x Q.",
    typical:
      "A typical home needs around 1-2 kW. A small village: 50-200 kW.",
    effect:
      "Power is affected by all input parameters, especially head and flow rate.",
  },
  energyDaily: {
    title: "Daily Energy Output",
    description:
      "The estimated energy produced in 24 hours after applying capacity factor. Energy (kWh) = Power (kW) x 24 x Capacity Factor.",
    typical:
      "A household uses about 30 kWh/day.",
    effect:
      "Captures realistic generation instead of full-time 24x7 operation.",
  },
  energyYearly: {
    title: "Annual Energy Output",
    description:
      "The estimated energy produced over 8,760 hours after applying capacity factor. Measured in MWh/year.",
    typical:
      "A typical home uses around 10 MWh/year.",
    effect:
      "Useful for feasibility and revenue estimation.",
  },
  capacityFactor: {
    title: "Capacity Factor",
    description:
      "Capacity factor is the ratio of actual average generation to maximum continuous generation over time.",
    typical:
      "Hydropower commonly ranges around 30%-70% depending on hydrology and operations.",
    effect:
      "Higher capacity factor increases annual energy without changing installed power capacity.",
  },
  capacityFactorCard: {
    title: "Capacity Factor",
    description:
      "Ratio of actual to maximum possible annual energy output. Driven by plant type.",
    typical:
      "Typical range depends on plant type and hydrology conditions.",
    effect:
      "Used to convert theoretical output into realistic annual energy estimates.",
  },
  actualEnergyYearly: {
    title: "Actual Energy/Year",
    description:
      "Theoretical energy adjusted by capacity factor for real-world estimate.",
    typical:
      "Computed as P x 8760 x CF and reported in MWh/year.",
    effect:
      "Provides a realistic annual generation estimate for planning and feasibility.",
  },
  classification: {
    title: "Plant Classification",
    description:
      "International classification based on installed capacity: Pico (<5 kW), Micro (5-100 kW), Mini (100 kW-10 MW), Large (>10 MW).",
    typical:
      "Most grid energy comes from large plants; micro/pico are important for rural electrification.",
    effect:
      "Classification affects regulatory and interconnection requirements.",
  },
  turbine: {
    title: "Turbine Recommendation",
    description:
      "Recommended turbine type selected from head height range.",
    typical:
      "Pelton: >100m head. Francis: 30-100m. Kaplan: <30m.",
    effect:
      "Correct turbine selection helps maximize efficiency and lifespan.",
  },
};
