/**
 * Educational tooltip content for every input/output parameter
 */

export interface TooltipContent {
  title: string;
  description: string;
  typical: string;
  effect: string;
}

export const tooltips: Record<string, TooltipContent> = {
  // Input parameters
  head: {
    title: "Head (h)",
    description:
      "The vertical distance between the water surface in the reservoir and the turbine. Also called the 'water fall height' or 'hydraulic head'.",
    typical:
      "Low head: 2–30m (river dams). Medium head: 30–100m (reservoir dams). High head: 100–1000m+ (mountain installations).",
    effect:
      "Power output is directly proportional to head — doubling the head doubles the power output.",
  },
  flowRate: {
    title: "Flow Rate (Q)",
    description:
      "The volume of water passing through the turbine per second, measured in cubic meters per second (m³/s).",
    typical:
      "Micro plants: 0.1–5 m³/s. Mini plants: 5–50 m³/s. Large plants: 100–5000+ m³/s. The Amazon River flows at ~200,000 m³/s.",
    effect:
      "Power output is directly proportional to flow rate — doubling the flow doubles the power.",
  },
  efficiency: {
    title: "Turbine Efficiency (η)",
    description:
      "The ratio of useful mechanical energy output to the total energy of the water input. No turbine is 100% efficient due to friction, turbulence, and other losses.",
    typical:
      "Modern turbines: 85–95%. Pelton: 85–92%. Francis: 90–95%. Kaplan: 88–93%. Older/smaller installations: 60–80%.",
    effect:
      "Efficiency directly scales the power output. The difference between 70% and 90% efficiency is ~29% more power.",
  },
  plantType: {
    title: "Plant Type",
    description:
      "The classification of the hydropower plant based on its installed capacity. Different plant sizes have different typical flow rates and infrastructure requirements.",
    typical:
      "Micro: <100 kW (small streams). Mini: 100 kW–10 MW (small rivers). Small: 10–30 MW. Large: >30 MW (major dams).",
    effect:
      "Selecting a plant type provides suggested flow rate ranges as a guideline for realistic parameter selection.",
  },

  // Output parameters
  powerOutput: {
    title: "Power Output (P)",
    description:
      "The theoretical power generated by the hydropower plant, calculated using P = η × ρ × g × h × Q. This is the instantaneous power at any given moment.",
    typical:
      "A typical home needs ~1–2 kW. A small village: 50–200 kW. A city of 100,000: ~100–500 MW.",
    effect:
      "Power is affected by all input parameters. Head and flow rate have the largest impact.",
  },
  energyDaily: {
    title: "Daily Energy Output",
    description:
      "The total energy produced in 24 hours assuming continuous operation at calculated power. Energy (kWh) = Power (kW) × Time (hours).",
    typical:
      "A household uses ~30 kWh/day. An electric car needs ~30–40 kWh for a full charge.",
    effect:
      "This assumes 24-hour operation. Actual output may vary with seasonal flow changes.",
  },
  energyYearly: {
    title: "Annual Energy Output",
    description:
      "The total energy produced over 8,760 hours (one year) assuming continuous operation. Measured in MWh/year.",
    typical:
      "Three Gorges Dam: ~100,000,000 MWh/year. A typical home uses ~10 MWh/year.",
    effect:
      "Annual output is key for economic feasibility studies. Multiply by electricity price for annual revenue.",
  },
  classification: {
    title: "Plant Classification",
    description:
      "International classification based on installed capacity: Pico (<5 kW), Micro (5–100 kW), Mini (100 kW–10 MW), Large (>10 MW).",
    typical:
      "Most of the world's hydropower comes from Large plants. Micro and Pico plants are important for rural electrification.",
    effect:
      "Classification determines regulatory requirements, grid connection standards, and financial incentives.",
  },
  turbine: {
    title: "Turbine Recommendation",
    description:
      "The recommended turbine type is selected based on the head height. Each turbine type is optimized for specific head and flow conditions.",
    typical:
      "Pelton: Mountain installations (>100m head). Francis: Most common worldwide (30–100m). Kaplan: Low-head river installations (<30m).",
    effect:
      "Choosing the correct turbine type is critical for maximizing efficiency and plant lifespan.",
  },
};
